MIN_AUMENTO_ENTRENAMIENTO = 0
MAX_AUMENTO_ENTRENAMIENTO = 100

AUMENTAR_VIDA_PLANTA = 12
AUMENTAR_ATAQUE_FUEGO = 15
AUMENTAR_VELOCIDAD_AGUA = 18

GASTO_ENERGIA_BAYA = 7
PROB_EXITO_BAYA = 0.8
GASTO_ENERGIA_POCION = 10
PROB_EXITO_POCION = 0.7
GASTO_ENERGIA_CARAMELO = 15
PROB_EXITO_CARAMELO = 0.6
AUMENTO_DEFENSA = 12

ENERGIA_ENTRENAMIENTO = 20
MIN_AUMENTO_EXPERIENCIA = 0
MAX_AUMENTO_EXPERIENCIA = 100

MEGA_VIDA = 50
MEGA_ATAQUE = 40
MEGA_DEFENSA = 45
MEGA_VELOCIDAD = 30
